{% set name = "google-cloud-bigtable" %}
{% set version = "2.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e8006c586905bd5c1947707376e55fdbd927299ef8d29ca756564018d0a6e26

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - google-cloud-core >=1.4.1,<3.0.0dev
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev
    - packaging >=14.3
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.0,<5.0.0dev

test:
  imports:
    - google.cloud.bigtable
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-bigtable
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python Client for Google Cloud Bigtable
  description: |
    Python Client for Google Cloud Bigtable
    -------------------------

    [Google Cloud Bigtable](https://cloud.google.com/bigtable) is Google's NoSQL Big Data database service. It's the
    same database that powers many core Google services, including Search,
    Analytics, Maps, and Gmail.

    - [Client Library Documentation](https://googleapis.github.io/google-cloud-python/latest/bigtable/usage.html)
    - [Product Documentation](https://cloud.google.com/bigtable/docs)

    Quick Start
    -----------

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Cloud Bigtable API.](https://cloud.google.com/bigtable)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    Supported Python Versions
    -------------------------
    Python >= 3.7

    Deprecated Python Versions
    -------------------------
    * Python 2.7: the last released version which supported Python 2.7 was version 1.7.0, released 2021-02-09.
    * Python 3.5: the last released version which supported Python 3.5 was version 1.7.0, released 2021-02-09.
    * Python 3.6: the last released version which supported Python 3.6 was version v2.10.1, released 2022-06-03.

  doc_url: https://googleapis.dev/python/bigtable/latest/index.html
  dev_url: https://github.com/googleapis/python-bigtable

extra:
  recipe-maintainers:
    - BrentDorsey
    - xylar
