schema_version: 1

context:
  name: google-cloud-bigtable
  version: 2.35.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: f5699012c5fea4bd4bdf7e80e5e3a812a847eb8f41bf8dc2f43095d6d876b83b

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - google-api-core >=2.17.0,<3.0.0
    - google-api-core-grpc
    - google-auth >=2.23.0,<3.0.0,!=2.24.0,!=2.25.0
    - google-cloud-core >=1.4.4,<3.0.0
    - grpc-google-iam-v1 >=0.12.4,<1.0.0
    # use the more restrictive constraint for python >=3.13
    - proto-plus >=1.25.0,<2.0.0
    - protobuf >=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - google-crc32c >=1.5.0,<2.0.0dev

tests:
  - python:
      imports:
        - google.cloud.bigtable
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Python Client for Google Cloud Bigtable
  description: |
    Python Client for Google Cloud Bigtable
    -------------------------

    [Google Cloud Bigtable](https://cloud.google.com/bigtable) is Google's NoSQL Big Data database service. It's the
    same database that powers many core Google services, including Search,
    Analytics, Maps, and Gmail.

    - [Client Library Documentation](https://googleapis.github.io/google-cloud-python/latest/bigtable/usage.html)
    - [Product Documentation](https://cloud.google.com/bigtable/docs)

    Quick Start
    -----------

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Cloud Bigtable API.](https://cloud.google.com/bigtable)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    Supported Python Versions
    -------------------------
    Python >= 3.7

    Deprecated Python Versions
    -------------------------
    * Python 2.7: the last released version which supported Python 2.7 was version 1.7.0, released 2021-02-09.
    * Python 3.5: the last released version which supported Python 3.5 was version 1.7.0, released 2021-02-09.
    * Python 3.6: the last released version which supported Python 3.6 was version v2.10.1, released 2022-06-03.

  homepage: https://github.com/googleapis/python-bigtable
  repository: https://github.com/googleapis/python-bigtable
  documentation: https://googleapis.dev/python/bigtable/latest/index.html

extra:
  recipe-maintainers:
    - BrentDorsey
    - xylar
