schema_version: 1

context:
  name: google-cloud-bigtable
  version: "2.38.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 0ad24f0106c2eb0f38e278b1641052e65882a4da0141d1f9ad78ea691724aaa3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - google-api-core >=2.11.0,<3.0.0
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0,!=2.24.0,!=2.25.0
    # more restrictive constraint for python >=3.14
    - grpcio >=1.75.1,<2.0.0
    # more restrictive constraint for python >=3.13
    - proto-plus >=1.25.0,<2.0.0
    - protobuf >=4.25.8,<8.0.0
    - google-cloud-core >=1.4.4,<3.0.0
    - grpc-google-iam-v1 >=0.12.4,<1.0.0
    - google-crc32c >=1.5.0,<2.0.0dev

tests:
  - python:
      imports:
        - google.cloud.bigtable
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Python Client for Google Cloud Bigtable
  description: |
    Python Client for Google Cloud Bigtable
    -------------------------

    [Google Cloud Bigtable](https://cloud.google.com/bigtable) is Google's NoSQL Big Data database service. It's the
    same database that powers many core Google services, including Search,
    Analytics, Maps, and Gmail.

    - [Client Library Documentation](https://googleapis.github.io/google-cloud-python/latest/bigtable/usage.html)
    - [Product Documentation](https://cloud.google.com/bigtable/docs)

    Quick Start
    -----------

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Cloud Bigtable API.](https://cloud.google.com/bigtable)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    Supported Python Versions
    -------------------------
    Python >= 3.7

    Deprecated Python Versions
    -------------------------
    * Python 2.7: the last released version which supported Python 2.7 was version 1.7.0, released 2021-02-09.
    * Python 3.5: the last released version which supported Python 3.5 was version 1.7.0, released 2021-02-09.
    * Python 3.6: the last released version which supported Python 3.6 was version v2.10.1, released 2022-06-03.

  homepage: https://github.com/googleapis/python-bigtable
  repository: https://github.com/googleapis/python-bigtable
  documentation: https://googleapis.dev/python/bigtable/latest/index.html

extra:
  recipe-maintainers:
    - BrentDorsey
    - xylar
